### ISSUE TITLE
Banner : "Contact us" layout is out of container

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#84] opened 2016-04-06 10:25 UTC
![2016-04-06_1452](https://cloud.githubusercontent.com/assets/13309730/14313582/fc68ab06-fc0f-11e5-8520-9af9a50d8ea7.png)

**Comment by euveng** [comment] 2016-04-13 03:12
The original design had only 4 form fields and the banner was built to accommodate those and the error message without exceeding the banner. Along the way, someone added a 5th form field and this breaks the design. Perhaps flag this as a post-live fix, this is not a bug and hence I won't fix.

**Closed** 2016-04-14 05:02 UTC
Labels: bug, wontfix
