### ISSUE TITLE
General: FOUC - Flash of unstyled content.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#26] opened 2016-03-09 14:10 UTC
![2016-03-09_1936foouucc](https://cloud.githubusercontent.com/assets/13309730/13637707/c5ecb050-e62e-11e5-9420-33b887f0aead.png)

**Comment by euveng** [comment] 2016-03-10 05:25
FOUC only occurs if the page stylesheets are enqueued in the footer. What you're seeing here is possibly a delay in the javascript initialising the slider - which happens after the dom is loaded. This could be because javascripts are enqueued in the footer, which cannot be avoided. Therefore this will be a won't fix issue.

**Comment by mahender-sowedane** [comment] 2016-03-10 08:53
Still FOUC exists. All banner images are displayed on page load.
Recurring issue, try disabling all your JS obviously banner got no style by default

![untitled-1acc](https://cloud.githubusercontent.com/assets/13309730/13664057/15db07a0-e6cb-11e5-9606-82ae8b49e3fe.png)
Tried disabling JS on this site and there will be a loading display not all the images displayed
![2016-03-10_1418](https://cloud.githubusercontent.com/assets/13309730/13664142/90c09f0c-e6cb-11e5-985a-c1b06f288abb.png)

**Comment by euveng** [comment] 2016-03-14 01:02
Hi, we were unable to reproduce the issue. To investigate further, can you advise if this occurs on the homepage or on all pages?

**Comment by mahender-sowedane** [comment] 2016-03-14 10:24
Sorry but FOUC in home page still recurring, Kindly follow the steps as shown above screenshot and observe the home page banner section.
thanks!

**Comment by euveng** [comment] 2016-03-15 03:12
Can you please answer my question?

**Comment by mahender-sowedane** [comment] 2016-03-15 07:37
Happens home page only, all banners are loaded. Layout is distorted

**Comment by euveng** [comment] 2016-03-22 06:54
Discussed and tested with Jo. This will be a won't fix.

**Closed** 2016-03-23 09:57 UTC
Labels: bug, wontfix
